[package]
name = "icrc30.mo"
version = "0.1.0"
description = "icrc30 for motoko"
repository = ""
keywords = [ "nft" ]
license = "MIT"

[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.10.0"
map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"
candy_0_3_0 = "https://github.com/icdevs/candy_library#v0.3.0@907a4e7363aac6c6a4e114ebc73e3d3f21e138af"
stablebuffer = "https://github.com/skilesare/StableBuffer#v0.2.0@110660769d11ba93c618dc4712525d20503bdc37"
stablebuffer_1_3_0 = "https://github.com/canscale/StableBuffer#v1.3.0@acdde6bb5b939227997cebdbb8919d2e6da8691c"
encoding_0_4_1 = "https://github.com/aviate-labs/encoding.mo#v0.4.1@2711d18727e954b11afc0d37945608512b5fbce2"
vector = "0.2.0"
rep-indy-hash = "0.1.0"

[dev-dependencies]
test = "1.0.1"
fuzz = "0.1.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
